# Generated by Django 4.2.4 on 2023-12-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0003_expense_expenseitem_expensesource_delete_userinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesource',
            name='source_name',
            field=models.CharField(max_length=100),
        ),
    ]
