# Generated by Django 4.2.4 on 2023-12-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0004_alter_expensesource_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
